#' Estimate larva stage
#'
#' This function returns an estimated larva stage for a folder number.
#' @param folder_nr Folder to test
#' @export
LarvaStage <- function (folder_nr, settings) {
  if ((folder_nr >= settings[[1]]@minFolder) & (folder_nr <= settings[[1]]@maxFolder))
    return (1)
  if ((folder_nr >= settings[[2]]@minFolder) & (folder_nr <= settings[[2]]@maxFolder))
    return (2)
  if (folder_nr >= settings[[3]]@minFolder)
    return (3)
}

#' Load all .csv files
#'
#' This function loads .csv files generated by ImageJ/Fiji and processes them
#' @param larvalcount How many objects are there
#' @param inpath Where to load the data from
#' @param outpath Where to save the data to
#' @param settings The settings to use for processing
#' @export
loadAllFiles <- function(larvalcount, inpath, outpath, settings) {
  if (any(c(missing(larvalcount), missing(settings), missing(inpath), missing(outpath)))) {
    print("All parameters are mandatory!")
    larvalcount = NULL;
    Settings = NULL;
    inpath = NULL;
    outpath = NULL;
    return(NULL)
  }
  for (k in 1:larvalcount) {

    larvanumber = paste("Larva", as.character(k), sep = "") # define larva
    print(sprintf("Running analysis on animal %02s", k))

    allfilenames <- list.files (inpath, pattern = paste(larvanumber, "_[0-9][0-9]_[0-2]_results.csv", sep = ""))
    csvfilelist <- list ()

    # reading csv files
    for (i in 1:length(allfilenames)){
      csvfilelist[[i]] = read.csv(paste(inpath,allfilenames[i], sep =""), sep = ",")
    }

    batchnumbers <- integer(length(allfilenames))

    for (i in 1:length(allfilenames)) {
      #find position of number
      pos = regexpr(larvanumber, allfilenames[i])+7

      if (k > 9) pos = pos + 1
      value <- substr (allfilenames[i], pos, pos+1)
      print (value)
      batchnumbers[i] = as.integer(value)
    }
    maxFolder <- max(batchnumbers)

    #logical vector (boolean)
    batchcounters = as.data.frame(table(batchnumbers))

    # How often has each batch been analyzed (1 or 2)
    a <- batchcounters$Freq == 1
    batchcounters$batchnumbers [a]
    inds <- which (batchnumbers %in% batchcounters$batchnumbers[a])

    csvfiles <- list(length(maxFolder))
    csvfilenames <- list(length(maxFolder))
    csvfiles [batchcounters$batchnumbers[a]] <- csvfilelist[inds]
    csvfilenames[batchcounters$batchnumbers[a]] <- allfilenames[inds]

    # Pick better fitting results, look at solidity value
    SolComp <- vector(mode = "list", length = sum(duplicated(batchnumbers)))
    names(SolComp) <- c(batchnumbers[duplicated(batchnumbers)])

    for (m in 1:sum(duplicated(batchnumbers))) {
      idx = names(SolComp[m])
      idx2 <- which (batchnumbers %in% idx)
      Sol1 <- if ((nrow(csvfilelist[[idx2[1]]])) == 0) Inf else mean(csvfilelist[[idx2[1]]]$Solidity)
      Sol2 <- if ((nrow(csvfilelist[[idx2[2]]])) == 0) Inf else mean(csvfilelist[[idx2[2]]]$Solidity)
      SolComp[idx] <- if (Sol1 < Sol2) 1 else 2
      g <- SolComp[[idx]]
      csvfiles [as.integer(idx)] <- csvfilelist[idx2[g]]
      csvfilenames [as.integer(idx)] <- allfilenames[idx2[g]]
    }

    for (i in 1:length(csvfiles)) {
      Data_Table <- csvfiles[[i]]

      Data_Table2 <-
        dplyr::select (Data_Table, one_of(
          c("Area", "X", "Y", "Major", "Minor", "Circ.", "RawIntDen", "Slice", "AR", "Round", "Solidity")
        ))

      colnames (Data_Table2) <-
        c("Area", "X", "Y", "Major", "Minor", "Circularity", "Raw", "ID", "AspectRatio", "Roundness", "Solidity")

      Data_Table2$ID <- as.numeric (Data_Table2$ID)
      Data_Table2$Area <- as.numeric (Data_Table2$Area)
      Data_Table2$Raw <- as.numeric (Data_Table2$Raw)
      Data_Table2$Major <- as.numeric (Data_Table2$Major)
      Data_Table2$Minor <- as.numeric (Data_Table2$Minor)

      size = LarvaStage(i)
      CurrentSettings <- settings[[size]]
      LarvaLodge_First <- subset (
        Data_Table2, Area >= CurrentSettings@Area,
        select = c(ID, Area, Major, Minor, Circularity, AspectRatio, Roundness, Solidity, X, Y)
      )

      LarvaLodge_Clean <-
        (data.table::setDT(LarvaLodge_First)[, .SD[which.max(LarvaLodge_First$Solidity)], by = ID])

      LarvaLodge_Final <-
        setNames(data.table(matrix(nrow = databins, ncol = 10)),
                 c("ID", "Area", "Major", "Minor", "Circularity", "AspectRatio", "Roundness", "Solidity", "X", "Y")
        )

      LarvaLodge_Final$ID <- as.numeric (1:databins)

      for (j in seq (1, nrow(LarvaLodge_Clean))) {
        ID <- LarvaLodge_Clean$ID [j]
        LarvaLodge_Final$ID [ID] <- LarvaLodge_Clean$ID [j]
        LarvaLodge_Final$Area [ID] <- LarvaLodge_Clean$Area [j]
        LarvaLodge_Final$Major [ID] <- LarvaLodge_Clean$Major [j]
        LarvaLodge_Final$Minor [ID] <- LarvaLodge_Clean$Minor [j]
        LarvaLodge_Final$Circularity [ID] <- LarvaLodge_Clean$Circularity [j]
        LarvaLodge_Final$AspectRatio [ID] <- LarvaLodge_Clean$AspectRatio [j]
        LarvaLodge_Final$Roundness [ID] <- LarvaLodge_Clean$Roundness [j]
        LarvaLodge_Final$Solidity [ID] <- LarvaLodge_Clean$Solidity [j]
        LarvaLodge_Final$X [ID] <- LarvaLodge_Clean$X [j]
        LarvaLodge_Final$Y [ID] <- LarvaLodge_Clean$Y [j]
      }

      outpath = paste(targetpath, stringr::str_replace(my.filesnames[i], "_results", "_analysis"), sep = "")
      write.csv (LarvaLodge_Final, outpath)

    }

    my.data <- list.files (targetpath, pattern = paste(larvanumber, "_[0-9][0-9]_[0-2]_analysis.csv", sep = ""))

    for (n in 1:length (my.data))
      assign (my.data[n], read.csv(paste(targetpath, my.data[n], sep = ""), sep = ","))

    row_bind = paste ("rbind(", paste (ls(
      pattern = paste(larvanumber, "_[0-9][0-9]_[0-2]_analysis.csv", sep = "")
    ), collapse = ","), ")")

    LarvaLodge_End = eval (parse(file = "", text = row_bind))

    outpath = paste(targetpath, "Larva", as.character(k), "_all.csv", sep = "")
    write.csv (LarvaLodge_End, outpath)
   }
}
